# Site settings
author: Ben Shapiro
title: My Flatiron Blog
header-img: img/home-bg.png
email: bshap93@gmail.com
copyright_name: Ben Shapiro
description: > # this means to ignore newlines until "baseurl:"
  Posts from 2016-2018
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: bshap93
github_username:  bshap93

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
